[[unitTest]]

name = "apsteering"

[[unitTest.test]]

RPC = """
<edit-config>
    <target>
        <running/>
    </target>
    <config>
        <apsteering xmlns="http://terastrm.net/ns/yang/terastream-wireless">
            <enabled>true</enabled>
            <monitor_interval>15</monitor_interval>
            <rssi_threshold>-85</rssi_threshold>
            <reassoc_timer>15</reassoc_timer>
            <retry_interval>3605</retry_interval>
        </apsteering>
    </config>
</edit-config>
"""

Reply = """<ok/>"""

[[unitTest.test]]

RPC = """
<get>
    <filter  xmlns:terastream-wireless='http://terastrm.net/ns/yang/terastream-wireless'  type="xpath" select="/terastream-wireless:apsteering">
    </filter>
</get>
"""

Reply = """<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><apsteering xmlns="http://terastrm.net/ns/yang/terastream-wireless"><enabled>true</enabled><monitor_interval>15</monitor_interval><rssi_threshold>-85</rssi_threshold><reassoc_timer>15</reassoc_timer><retry_interval>3605</retry_interval></apsteering></data>"""

[[unitTest.test]]

RPC = """
  <call xmlns="urn:ietf:params:xml:ns:yang:test-plugin">
    <command>uci show wireless.apsteering</command>
  </call>
"""

Reply = """<response xmlns="urn:ietf:params:xml:ns:yang:test-plugin">wireless.apsteering=apsteering
wireless.apsteering.enabled='1'
wireless.apsteering.monitor_interval='15'
wireless.apsteering.rssi_threshold='-85'
wireless.apsteering.reassoc_timer='15'
wireless.apsteering.retry_interval='3605'
</response>"""

[[unitTest]]

name = "bandsteering"

[[unitTest.test]]

RPC = """
<edit-config>
    <target>
        <running/>
    </target>
    <config>
        <bandsteering xmlns="http://terastrm.net/ns/yang/terastream-wireless">
            <enabled>true</enabled>
            <policy>true</policy>
            <rssi_threshold>-70</rssi_threshold>
            <bw_util>65</bw_util>
        </bandsteering>
    </config>
</edit-config>
"""

Reply = """<ok/>"""

[[unitTest.test]]

RPC = """
<get>
    <filter  xmlns:terastream-wireless='http://terastrm.net/ns/yang/terastream-wireless'  type="xpath" select="/terastream-wireless:bandsteering">
    </filter>
</get>
"""

Reply = """<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><bandsteering xmlns="http://terastrm.net/ns/yang/terastream-wireless"><enabled>true</enabled><policy>true</policy><rssi_threshold>-70</rssi_threshold><bw_util>65</bw_util></bandsteering></data>"""

[[unitTest.test]]

RPC = """
  <call xmlns="urn:ietf:params:xml:ns:yang:test-plugin">
    <command>uci show wireless.bandsteering</command>
  </call>
"""

Reply = """<response xmlns="urn:ietf:params:xml:ns:yang:test-plugin">wireless.bandsteering=bandsteering
wireless.bandsteering.enabled='1'
wireless.bandsteering.policy='0'
wireless.bandsteering.rssi_threshold='-75'
</response>"""

### devices ###
[[unitTest]]

name = "devices"

[[unitTest.test]]
### set the device wl0

RPC = """
<edit-config>
    <target>
        <running/>
    </target>
    <config>
        <devices xmlns="http://terastrm.net/ns/yang/terastream-wireless">
            <device>
                <name>wl0</name>
                <type>true</type>
                <country>EU/12</country>
                <frequencyband>5</frequencyband>
                <bandwidth>40</bandwidth>
                <channel>11</channel>
                <obss_coex>true</obss_coex>
                <scantimer>14</scantimer>
                <wmm>true</wmm>
                <wmm_noack>false</wmm_noack>
                <txpower>50</txpower>
                <rateset>default</rateset>
                <frag>2342</frag>
                <rts>2345</rts>
                <dtim_period>1</dtim_period>
                <beacon_int>100</beacon_int>
                <rxchainps>false</rxchainps>
                <rxchainps_qt>20</rxchainps_qt>
                <rxchainps_pps>20</rxchainps_pps>
                <rifs>false</rifs>
                <rifs_advert>false</rifs_advert>
                <maxassoc>30</maxassoc>
                <dfsc>true</dfsc>
                <hwmode>auto</hwmode>
                <enabled>true</enabled>
                <frameburst>false</frameburst>
                <beamforming>true</beamforming>
                <atf>false</atf>
                <doth>2</doth>
                <interface>
                    <name>cfg053579</name>
                    <device>wl0</device>
                    <ifname>wl0</ifname>
                    <network>lan</network>
                    <mode>ap</mode>
                    <ssid>PANTERA-E302</ssid>
                    <encryption>psk2</encryption>
                    <cipher>auto</cipher>
                    <key>keykeykey</key>
                    <gtk_rekey>360</gtk_rekey>
                    <net_reauth>3600</net_reauth>
                    <wps_pbc>false</wps_pbc>
                    <wmf_bss_enable>true</wmf_bss_enable>
                    <bss_max>30</bss_max>
                    <closed>false</closed>
                    <isolate>false</isolate>
                    <enabled>false</enabled>
                    <macfilter>0</macfilter>
                    <hidden>true</hidden>
                </interface>
            </device>
            <device>
                <name>wl1</name>
                <type>true</type>
                <country>EU/11</country>
                <frequencyband>2.4</frequencyband>
                <bandwidth>20</bandwidth>
                <channel>11</channel>
                <obss_coex>true</obss_coex>
                <scantimer>14</scantimer>
                <wmm>true</wmm>
                <wmm_noack>false</wmm_noack>
                <txpower>60</txpower>
                <rateset>default</rateset>
                <frag>2342</frag>
                <rts>2342</rts>
                <dtim_period>2</dtim_period>
                <beacon_int>100</beacon_int>
                <rxchainps>false</rxchainps>
                <rxchainps_qt>20</rxchainps_qt>
                <rxchainps_pps>20</rxchainps_pps>
                <rifs>false</rifs>
                <rifs_advert>false</rifs_advert>
                <maxassoc>32</maxassoc>
                <dfsc>true</dfsc>
                <hwmode>auto</hwmode>
                <enabled>true</enabled>
                <frameburst>false</frameburst>
                <beamforming>false</beamforming>
                <atf>false</atf>
                <doth>1</doth>
                <interface>
                    <name>cfg083579</name>
                    <device>wl1</device>
                    <ifname>wl1</ifname>
                    <network>lan</network>
                    <mode>ap</mode>
                    <ssid>PANTERA-E302</ssid>
                    <encryption>psk2</encryption>
                    <cipher>auto</cipher>
                    <key>keykeykey</key>
                    <gtk_rekey>360</gtk_rekey>
                    <net_reauth>3600</net_reauth>
                    <wps_pbc>false</wps_pbc>
                    <wmf_bss_enable>true</wmf_bss_enable>
                    <bss_max>31</bss_max>
                    <closed>false</closed>
                    <isolate>false</isolate>
                    <enabled>false</enabled>
                    <macfilter>0</macfilter>
                    <hidden>false</hidden>
                </interface>
            </device>
        </devices>
    </config>
</edit-config>
"""

Reply = """<ok/>"""

[[unitTest.test]]
### set the device wl0

RPC = """
<edit-config>
    <target>
        <running/>
    </target>
    <config>
        <devices xmlns="http://terastrm.net/ns/yang/terastream-wireless">
            <device>
                <name>wl0</name>
                <type>true</type>
                <country>EU/12</country>
                <frequencyband>5</frequencyband>
                <bandwidth>40</bandwidth>
                <channel>11</channel>
                <obss_coex>true</obss_coex>
                <scantimer>14</scantimer>
                <wmm>true</wmm>
                <wmm_noack>false</wmm_noack>
                <txpower>50</txpower>
                <rateset>default</rateset>
                <frag>2342</frag>
                <rts>2345</rts>
                <dtim_period>1</dtim_period>
                <beacon_int>100</beacon_int>
                <rxchainps>false</rxchainps>
                <rxchainps_qt>20</rxchainps_qt>
                <rxchainps_pps>20</rxchainps_pps>
                <rifs>false</rifs>
                <rifs_advert>false</rifs_advert>
                <maxassoc>30</maxassoc>
                <dfsc>true</dfsc>
                <hwmode>auto</hwmode>
                <enabled>true</enabled>
                <frameburst>false</frameburst>
                <beamforming>true</beamforming>
                <atf>false</atf>
                <doth>2</doth>
            </device>
        </devices>
    </config>
</edit-config>
"""

Reply = """<ok/>"""

[[unitTest.test]]

RPC = """
<get>
    <filter  xmlns:terastream-wireless='http://terastrm.net/ns/yang/terastream-wireless'  type="xpath" select="/terastream-wireless:devices/device[name='wl0']">
    </filter>
</get>
"""

Reply = """<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><devices xmlns="http://terastrm.net/ns/yang/terastream-wireless"><device><name>wl0</name><type>true</type><country>EU/12</country><frequencyband>5</frequencyband><bandwidth>40</bandwidth><channel>11</channel><obss_coex>true</obss_coex><scantimer>14</scantimer><wmm>true</wmm><wmm_noack>false</wmm_noack><txpower>50</txpower><rateset>default</rateset><frag>2342</frag><rts>2345</rts><dtim_period>1</dtim_period><beacon_int>100</beacon_int><rxchainps>false</rxchainps><rxchainps_qt>20</rxchainps_qt><rxchainps_pps>20</rxchainps_pps><rifs>false</rifs><rifs_advert>false</rifs_advert><maxassoc>30</maxassoc><dfsc>true</dfsc><hwmode>auto</hwmode><enabled>true</enabled><frameburst>false</frameburst><beamforming>true</beamforming><atf>false</atf><doth>2</doth><interface><name>cfg053579</name><device>wl0</device><ifname>wl0</ifname><network>lan</network><mode>ap</mode><ssid>PANTERA-E302</ssid><encryption>psk2</encryption><cipher>auto</cipher><key>keykeykey</key><gtk_rekey>360</gtk_rekey><net_reauth>3600</net_reauth><wps_pbc>false</wps_pbc><wmf_bss_enable>true</wmf_bss_enable><bss_max>30</bss_max><closed>false</closed><isolate>false</isolate><enabled>false</enabled><macfilter>0</macfilter><hidden>true</hidden></interface></device></devices></data>"""

[[unitTest.test]]

RPC = """
  <call xmlns="urn:ietf:params:xml:ns:yang:test-plugin">
    <command>uci show wireless.wl0</command>
  </call>
"""

Reply = """<response xmlns="urn:ietf:params:xml:ns:yang:test-plugin">wireless.wl0=wifi-device
wireless.wl0.type='broadcom'
wireless.wl0.band='a'
wireless.wl0.hwmode='auto'
wireless.wl0.rateset='default'
wireless.wl0.dtim_period='1'
wireless.wl0.beacon_int='100'
wireless.wl0.disabled='0'
wireless.wl0.wmm_apsd='true'
wireless.wl0.country='EU/12'
wireless.wl0.bandwidth='40'
wireless.wl0.channel='11'
wireless.wl0.obss_coex='0'
wireless.wl0.scantimer='14'
wireless.wl0.wmm='0'
wireless.wl0.wmm_noack='1'
wireless.wl0.txpower='50'
wireless.wl0.frag='2342'
wireless.wl0.rts='2345'
wireless.wl0.rxchainps='1'
wireless.wl0.rxchainps_qt='20'
wireless.wl0.rxchainps_pps='20'
wireless.wl0.rifs='1'
wireless.wl0.rifs_advert='1'
wireless.wl0.maxassoc='30'
wireless.wl0.dfsc='0'
wireless.wl0.frameburst='1'
wireless.wl0.beamforming='0'
wireless.wl0.atf='1'
wireless.wl0.doth='2'
</response>"""

[[unitTest.test]]

RPC = """
  <call xmlns="urn:ietf:params:xml:ns:yang:test-plugin">
    <command>uci show wireless.cfg053579</command>
  </call>
"""

Reply = """<response xmlns="urn:ietf:params:xml:ns:yang:test-plugin">wireless.cfg053579=wifi-iface
wireless.cfg053579.device='wl0'
wireless.cfg053579.network='lan'
wireless.cfg053579.mode='ap'
wireless.cfg053579.ssid='PANTERA-E302'
wireless.cfg053579.encryption='psk2'
wireless.cfg053579.cipher='auto'
wireless.cfg053579.macfilter='0'
wireless.cfg053579.ifname='wl0'
wireless.cfg053579.key='keykeykey'
wireless.cfg053579.gtk_rekey='360'
wireless.cfg053579.net_reauth='3600'
wireless.cfg053579.wps_pbc='1'
wireless.cfg053579.wmf_bss_enable='0'
wireless.cfg053579.bss_max='30'
wireless.cfg053579.closed='1'
wireless.cfg053579.isolate='1'
wireless.cfg053579.disabled='1'
</response>"""

[[unitTest.test]]

RPC = """
  <call xmlns="urn:ietf:params:xml:ns:yang:test-plugin">
    <command>uci show wireless.wl1</command>
  </call>
"""

Reply = """<response xmlns="urn:ietf:params:xml:ns:yang:test-plugin">wireless.wl1=wifi-device
wireless.wl1.type='broadcom'
wireless.wl1.band='b'
wireless.wl1.bandwidth='20'
wireless.wl1.hwmode='auto'
wireless.wl1.rateset='default'
wireless.wl1.beacon_int='100'
wireless.wl1.maxassoc='32'
wireless.wl1.disabled='0'
wireless.wl1.wmm_apsd='true'
wireless.wl1.country='EU/11'
wireless.wl1.channel='11'
wireless.wl1.obss_coex='0'
wireless.wl1.scantimer='14'
wireless.wl1.wmm='0'
wireless.wl1.wmm_noack='1'
wireless.wl1.txpower='60'
wireless.wl1.frag='2342'
wireless.wl1.rts='2342'
wireless.wl1.dtim_period='2'
wireless.wl1.rxchainps='1'
wireless.wl1.rxchainps_qt='20'
wireless.wl1.rxchainps_pps='20'
wireless.wl1.rifs='1'
wireless.wl1.rifs_advert='1'
wireless.wl1.dfsc='0'
wireless.wl1.frameburst='1'
wireless.wl1.beamforming='1'
wireless.wl1.atf='1'
wireless.wl1.doth='1'
</response>"""

[[unitTest.test]]

RPC = """
  <call xmlns="urn:ietf:params:xml:ns:yang:test-plugin">
    <command>uci show wireless.cfg083579</command>
  </call>
"""

Reply = """<response xmlns="urn:ietf:params:xml:ns:yang:test-plugin">wireless.cfg083579=wifi-iface
wireless.cfg083579.device='wl1'
wireless.cfg083579.network='lan'
wireless.cfg083579.mode='ap'
wireless.cfg083579.ssid='PANTERA-E302'
wireless.cfg083579.encryption='psk2'
wireless.cfg083579.cipher='auto'
wireless.cfg083579.macfilter='0'
wireless.cfg083579.ifname='wl1'
wireless.cfg083579.key='keykeykey'
wireless.cfg083579.gtk_rekey='360'
wireless.cfg083579.net_reauth='3600'
wireless.cfg083579.wps_pbc='1'
wireless.cfg083579.wmf_bss_enable='0'
wireless.cfg083579.bss_max='31'
wireless.cfg083579.closed='1'
wireless.cfg083579.isolate='1'
wireless.cfg083579.disabled='1'
wireless.cfg083579.hidden='1'
</response>"""
